name: CI of pistop-customer microservice
#DÃ©clencher le pipline si une modification fait dans le pistop-customer microserv
on:
  push:
    paths:
      - 'pitstop-customer/**'
  workflow_dispatch:


jobs:
  build:
    # Ensure the runner is using the latest Ubuntu version

    runs-on: ubuntu-latest  

    steps:
      - name: "Checkout the code to the runner"
        uses: actions/checkout@v4

      - name: "Build Docker image"
        run: |
          cd  pitstop-customer  
          docker build -t  ${{secrets.DOCKER_USERNAME }}/pitstop-customer .  
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Push the image to Docker Hub"
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/pitstop-customer
